### Find all content
GET http://localhost:8080/api/content

### Get content by id
GET http://localhost:8080/api/content/2

### Create new content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "Hello World 2",
  "desc": "This is the 2nd test",
  "price": 200,
  "image": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
}

### Update existing content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "Hello World 1",
  "desc": "This is the 1st test",
  "price": 100,
  "image": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
}

### Delete existing content by ID
DELETE http://localhost:8080/api/content/1
